host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: 这里写联系人信息
    url: http://www.swagger.io/support
  description: 这里写描述信息
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 这里写标题
  version: "1.0"
paths:
  /userLogin:
    post:
      description: 用户登录接口，返回token
      parameters:
      - description: mobile
        in: path
        name: mobile
        required: true
        type: string
      - description: password
        in: path
        name: password
        required: true
        type: string
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 用户信息
  /userRegister:
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 用户注册
swagger: "2.0"
